repos:
  - repo: local
    hooks:
    - id: conventional-pre-commit
      name: conventional-pre-commit
      always_run: true
      entry: poetry run python3 hooks/conventional-pre-commit.py
      language: system
      stages: [commit-msg]

    - id: PEP-672
      name: PEP-672
      stages: [manual]
      entry: poetry run python3 hooks/check_pep672_ascii.py
      language: system

    - id: forbidden-files
      name: forbidden-files
      stages: [manual]
      entry: poetry run python3 hooks/forbidden_files.py
      language: system
      pass_filenames: false
      args: ["-f", "hooks/forbidden_files.py"]
